# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.powernode.ssmdemo.bean

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
logging:
  pattern:
    console: level-%-5level - %msg%n
  level:
    root: warn
    com.powernode.ssmdemo.mapper: debug
